# -*- coding: utf-8 -*-
"""Tugas-12_Hilmi Mufid_250506046_RO 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R6N84BNWtcQ1WXPgmVsucMZFpqgOey_G
"""

# PERSEGI PANJANG
print("LUAS PERSEGI PANJANG")
def persegi_panjang(panjang, lebar):
  return panjang * lebar

panjang = int(input("masukan panjangnya : "))
lebar = int(input("masukan lebarnnya : "))
luas = panjang * lebar


print(f"hasil luas nya : {luas}\n")

# VOLUME BALOK
print("VOLUME BALOK")
def balok(panjang, lebar, tinggi):
  return panjang * lebar * tinggi

panjang = int(input("masukan panjangnya : "))
lebar = int(input("masukan lebarnnya : "))
tinggi = int(input("masukan tingginya : "))
volume = panjang * lebar * tinggi

print(f"hasil volume nya : {volume}\n")

# Luas lingkaran
print("LUAS LINGKARAN")
import math

def lingkaran(jari_jari):
  return math.pi * (jari_jari ** 2)

jari2 = int(input("masukan jari jari : "))

luas = math.pi * (jari2 ** 2)
print(f"hasil luas nya : {luas:.2f}\n")

# Volume Bola1
print("VOLUME BOLA")
def vol_bola(jari_jari):
   return (4/3) * math.pi * (jari_jari ** 3)

jari3 = int(input("masukan jari jari : "))
volume = (4/3) * math.pi * (jari3 ** 3)

print(f"hasil volume nya : {volume:.2f}\n")

ty = "done"
print(f"alhamdulillah {ty}")

